INSERT INTO APARTMENT (ID,STREET_NAME,APARTMENT_NAME,APARTMENT_NUMBER,PROVINCE,DISTRICT)
VALUES (1L,'StreetName1','Enes',1,'Istanbul','Ataşehir') ,
       (2L,'StreetName2','Mahmut',2,'Istanbul','Ataşehir');

INSERT INTO RENTER (ID,NAME,SURNAME,PHONE_NUMBER,TCKN)
VALUES (1L,'Enes','Bingöl',112344,1L),
       (2L,'Ali','Bingöl',121312,2L);

INSERT INTO FLAT (ID,APARTMENT_ID,FLAT_NUMBER,RENTER_ID)
VALUES (1L,1L,10,1L),
       (2L,1L,11,2L);
